### ISSUE TITLE
hook.error is not a function - problem with beforeEach

### ISSUE THREAD

**Issue by kamiloski** [sskorol/mocha-allure2-reporter#6]
If in my test file exist beforeEach I get en error in console and performing of test stops.
Any idea whats is wrong? I use cypress with typescript on windows. With previous verion of aalure v1 I havnt sililar issue. I run test using script:
`./node_modules/.bin/cypress run --reporter mocha-allure2-reporter mocha --headed`
Here is my log from terminal 
`TypeError: hook.error is not a function
    at MochaAllureReporter.onHookEnd (...\node_modules\mocha-allure2-reporter\src\MochaAllureReporter.js:63:29)
    at Runner.emit (events.js:208:15)
    at Reporter.emit (...\Cypress\Cache\3.8.3\Cypress\resources\app\packages\server\lib\reporter.js:234:55)
    at Object.onMocha (...\Cypress\Cache\3.8.3\Cypress\resources\app\packages\server\lib\project.js:359:18)
    at Socket.<anonymous> (...\Cypress\Cache\3.8.3\Cypress\resources\app\packages\server\lib\socket.js:303:32)
    at Socket.emit (events.js:203:13)
    at ...Cypress\Cache\3.8.3\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)`

**Comment by sskorol** [comment]
@kamiloski can you show you package.json dependencies? Do you also have a minimal working example to reproduce the issue? Does it work without cypress?

**Comment by kamiloski** [comment]
Dependencies:
` "dependencies": {},
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^4.1.1",
    "@types/fs-extra": "^8.0.1",
    "@types/klaw-sync": "^6.0.0",
    "@types/lodash": "^4.14.149",
    "@types/node": "^13.7.0",
    "allure-commandline": "^2.13.0",
    "cypress": "^3.8.3",
    "klaw-sync": "^6.0.0",
    "mocha": "^4.1.0",
    "mocha-allure2-reporter": "0.0.3",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^4.0.0",
    "mochawesome-report-generator": "^4.1.0",
    "npm-run-all": "^4.1.5",
    "rimraf": "^3.0.1",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5",
    "webpack": "^4.41.5"
  },
  "scripts": {
    "test:all": "./node_modules/.bin/cypress run --reporter mocha-allure2-reporter mocha --headed",
  },`

simple test where issue occurs - test.ts file:
`describe('test_1', () => {
    beforeEach(() => {
        cy.visit('https://www.google.pl/')
    })
    it('test_1_1', () => {
        cy.url().should('contain', 'google')
    })
})`

As i said when i was using mocha-allure-reporter (version 1) then was no problem, after update to version 2 it error appear

**Comment by sskorol** [comment]
@kamiloski I see you're using Mocha 4.1.0. However, this project requires Mocha ^5.2.0 as a peer dependency. Please try to update Mocha first.

**Comment by kamiloski** [comment]
I have just updated to "mocha": "^7.0.1" and error still occurs

**Comment by kamiloski** [comment]
Here is my very simple repo, I created it few minutes ago, on other computer and this tiime on Ubuntu, but have the same problem
https://github.com/kamiloski/cypress-hook
npm install
and run tests -> npm run test:mocha
And error appears

**Comment by kamiloski** [comment]
@sskorol any solution? I need this functionality it's very important to me

**Comment by sskorol** [comment]
@kamiloski I can reproduce your issue. But I believe the issue itself comes from Cypress. First of all, there's an interesting trace in a `Hook` object that is injected into before/after hooks:
```
{
  title: '"before all" hook',
  fn: [Function: fn] { toString: [Function] },
  async: undefined,
  sync: undefined,
  _timeout: 2000,
  _slow: 75,
  _enableTimeouts: true,
  timedOut: undefined,
  _trace: Error: done() called multiple times
      at Test.Runnable (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/mocha/lib/runnable.js:54:17)
      at new Test (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/mocha/lib/test.js:22:12)
      at createRunnable (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:73:16)
      at Reporter.<anonymous> (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:220:20)
      at Reporter._createRunnable (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:224:10)
      at /Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:210:30
      at arrayMap (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:639:23)
      at Function.map (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9554:14)
      at Reporter.<anonymous> (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:208:29)
      at Reporter._createRunnable (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:224:10)
      at /Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:215:30
      at arrayMap (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:639:23)
      at Function.map (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9554:14)
      at Reporter.<anonymous> (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:213:30)
      at Reporter._createRunnable (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:224:10)
      at Reporter.setRunnables (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:189:27)
      at Object.onSetRunnables (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:347:20)
      at Socket.<anonymous> (/Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:299:17)
      at Socket.emit (events.js:203:13)
      at /Users/skorol/Library/Caches/Cypress/4.0.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
      at processTicksAndRejections (internal/process/task_queues.js:75:11)
  ,
  _retries: -1,
  _currentRetry: 0,
  pending: false,
  type: 'hook',
  body: "function () {\n    cy.visit('https://www.google.pl/');\n  }",
  duration: 907,
  state: 'skipped',
  parent: Suite {
    title: 'telala',
    ctx: {},
    suites: [],
    tests: [ [Test] ],
    pending: false,
    _beforeEach: [],
    _beforeAll: [],
    _afterEach: [],
    _afterAll: [],
    root: false,
    _timeout: 2000,
    _enableTimeouts: true,
    _slow: 75,
    _bail: false,
    _retries: -1,
    delayed: false,
    parent: Suite {
      title: '',
      ctx: {},
      suites: [Array],
      tests: [],
      pending: false,
      _beforeEach: [],
      _beforeAll: [],
      _afterEach: [],
      _afterAll: [],
      root: true,
      _timeout: 2000,
      _enableTimeouts: true,
      _slow: 75,
      _bail: false,
      _retries: -1,
      delayed: false,
      file: 'cypress/integration/wyk.js',
      id: 'r1',
      type: 'suite'
    },
    file: null,
    id: 'r2',
    type: 'suite'
  },
  id: 'r3',
  clone: [Function],
  timeout: [Function],
  slow: [Function],
  enableTimeouts: [Function],
  skip: [Function],
  retries: [Function],
  currentRetry: [Function],
  fullTitle: [Function],
  clearTimeout: [Function],
  inspect: [Function],
  resetTimeout: [Function],
  globals: [Function],
  run: [Function],
  titlePath: [Function],
  _events: undefined,
  _eventsCount: 0,
  _maxListeners: undefined,
  setMaxListeners: [Function: setMaxListeners],
  getMaxListeners: [Function: getMaxListeners],
  emit: [Function: emit],
  addListener: [Function: addListener],
  on: [Function: addListener],
  prependListener: [Function: prependListener],
  once: [Function: once],
  prependOnceListener: [Function: prependOnceListener],
  removeListener: [Function: removeListener],
  off: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners],
  listeners: [Function: listeners],
  rawListeners: [Function: rawListeners],
  listenerCount: [Function: listenerCount],
  eventNames: [Function: eventNames],
  hookName: 'before all',
  hookId: 'h1',
  file: null
}
```
Moreover, I can't see an `error()` method available in a `Hook` object. According to official Mocha [documentation](https://mochajs.org/api/tutorial-custom-reporter.html), `EVENT_HOOK_BEGIN` and `EVENT_HOOK_END` must pass a `Hook` argument. And if you drill into [Hook reference](https://mochajs.org/api/hook), you'll see that it has an `error` method.

Your stacktrace says that hook.error is not a function. It means that this method is missing in a `Hook` object. And you can actually see it in debug as well. So the main question is why it's missing only in the cypress-related projects? Coincidence? I don't believe so. I've also followed the Cypress trace to see its sources. And it seems like `Error: done() called multiple times` that is thrown by Mocha might be related to the ancient [Mocha dependency](https://github.com/cypress-io/cypress/blob/develop/packages/server/package.json#L85) in a Cypress server. When I checked Mocha issues for 2.4.x versions, I found the following related to [beforeEach hook](https://github.com/mochajs/mocha/issues/2136). So it's worth to update Mocha version on a Cypress server first. The possible root cause might be in bugs specific to a particular Mocha version.

P.S. Creating a workaround by removing `hook.error()` from after hook won't be an option as it violates the Mocha contract and may hide the potential Cypress issues. You can actually check this theory by creating your own tiny Mocha reporter with hooks and pass it to Cypress.

**Comment by kamiloski** [comment]
@sskorol so to whom should I report this issue? To cypress?

**Comment by sskorol** [comment]
@kamiloski yes, but it's better to create a minimal project for reproduction. I mean a single-file custom Mocha reporter with before/after hooks. I can't do it right now. But if you have troubles creating it by your own, I can do it this weekend for you.
